const options = [
  { Usuario: 'José Carlos da Silva', Nickname: 'jose_carlos10', Presença: true, ValordeCompra: 120 },
  { Usuario: 'Ana Paula Martins', Nickname: 'ana_paulam', Presença: false, ValordeCompra: 200 },
  { Usuario: 'Carlos Henrique Souza', Nickname: 'carlos_hs', Presença: true, ValordeCompra: 350 },
  { Usuario: 'Mariana Oliveira', Nickname: 'mariana_oli', Presença: true, ValordeCompra: 75 },
  { Usuario: 'Rafael Mendes', Nickname: 'rafa_mendes', Presença: false, ValordeCompra: 420 },
  { Usuario: 'Luciana Costa', Nickname: 'luciana_c', Presença: true, ValordeCompra: 180 },
  { Usuario: 'Fernanda Lima', Nickname: 'fernanda_l', Presença: false, ValordeCompra: 95 },
  { Usuario: 'João Pedro Rocha', Nickname: 'joao_pedro', Presença: true, ValordeCompra: 260 },
  { Usuario: 'Tatiane Barbosa', Nickname: 'tatiane_brb', Presença: false, ValordeCompra: 130 },
  { Usuario: 'Ricardo Santos', Nickname: 'ric_santos', Presença: true, ValordeCompra: 400 },
  { Usuario: 'Paula Regina Campos', Nickname: 'paula_regina', Presença: false, ValordeCompra: 60 },
  { Usuario: 'Bruno César Moreira', Nickname: 'bruno_cm', Presença: true, ValordeCompra: 150 },
  { Usuario: 'Débora Almeida', Nickname: 'debora.al', Presença: false, ValordeCompra: 300 },
  { Usuario: 'Tiago Nunes', Nickname: 'tiagon', Presença: true, ValordeCompra: 240 },
  { Usuario: 'Camila Freitas', Nickname: 'cami_freitas', Presença: false, ValordeCompra: 80 },
  { Usuario: 'Gustavo Araújo', Nickname: 'gust_araujo', Presença: true, ValordeCompra: 220 },
  { Usuario: 'Juliana Souza', Nickname: 'julianasz', Presença: true, ValordeCompra: 310 },
  { Usuario: 'Eduardo Lopes', Nickname: 'edu_lopes', Presença: false, ValordeCompra: 175 },
  { Usuario: 'Isabela Martins', Nickname: 'isamartins', Presença: true, ValordeCompra: 500 },
  { Usuario: 'Marcelo Ferreira', Nickname: 'marcelo_f', Presença: false, ValordeCompra: 140 },
  { Usuario: 'Lívia Fernandes', Nickname: 'liv_fernandes', Presença: true, ValordeCompra: 210 },
  { Usuario: 'André Luiz Ribeiro', Nickname: 'andre_lr', Presença: false, ValordeCompra: 95 },
  { Usuario: 'Renata Moura', Nickname: 'renata_moura', Presença: true, ValordeCompra: 160 },
  { Usuario: 'Sérgio Carvalho', Nickname: 'sergio_carv', Presença: false, ValordeCompra: 300 },
  { Usuario: 'Priscila Duarte', Nickname: 'priscila_d', Presença: true, ValordeCompra: 220 },
  { Usuario: 'Thiago Ramos', Nickname: 'thi_ramos', Presença: false, ValordeCompra: 150 },
  { Usuario: 'Carla Figueiredo', Nickname: 'carla_figue', Presença: true, ValordeCompra: 185 },
  { Usuario: 'Robson Andrade', Nickname: 'rob_andrade', Presença: true, ValordeCompra: 260 },
  { Usuario: 'Vanessa Rocha', Nickname: 'vanessaro', Presença: false, ValordeCompra: 75 },
  { Usuario: 'Felipe Martins', Nickname: 'felipem10', Presença: true, ValordeCompra: 320 },
  { Usuario: 'Natália Gomes', Nickname: 'nat_gomes', Presença: false, ValordeCompra: 130 },
  { Usuario: 'Diego Pires', Nickname: 'diegop', Presença: true, ValordeCompra: 200 },
  { Usuario: 'Larissa Brito', Nickname: 'lari_brito', Presença: false, ValordeCompra: 180 },
  { Usuario: 'Maurício Teixeira', Nickname: 'mauricio_tx', Presença: true, ValordeCompra: 440 },
  { Usuario: 'Patrícia Silva', Nickname: 'pat_silva', Presença: false, ValordeCompra: 110 },
  { Usuario: 'César Augusto', Nickname: 'cesar_aug', Presença: true, ValordeCompra: 275 },
  { Usuario: 'Juliane Tavares', Nickname: 'julitava', Presença: false, ValordeCompra: 150 },
  { Usuario: 'Matheus Castro', Nickname: 'mat_castro', Presença: true, ValordeCompra: 360 },
  { Usuario: 'Helena Moraes', Nickname: 'helena.m', Presença: false, ValordeCompra: 90 },
  { Usuario: 'Rogério Lima', Nickname: 'rogerlima', Presença: true, ValordeCompra: 410 },
  { Usuario: 'Elaine Souza', Nickname: 'elaine_s', Presença: false, ValordeCompra: 65 },
  { Usuario: 'Rodrigo Cunha', Nickname: 'rodcunha', Presença: true, ValordeCompra: 235 },
  { Usuario: 'Michele Araújo', Nickname: 'mich_ara', Presença: false, ValordeCompra: 140 },
  { Usuario: 'Pedro Henrique', Nickname: 'pedro.h', Presença: true, ValordeCompra: 295 },
  { Usuario: 'Simone Carvalho', Nickname: 'simonecarv', Presença: false, ValordeCompra: 85 },
  { Usuario: 'Luiz Otávio', Nickname: 'luizotavio', Presença: true, ValordeCompra: 315 },
  { Usuario: 'Aline Santana', Nickname: 'alinesant', Presença: false, ValordeCompra: 105 },
  { Usuario: 'Danilo Barros', Nickname: 'danilo_b', Presença: true, ValordeCompra: 390 },
  { Usuario: 'Beatriz Nogueira', Nickname: 'bia_nogueira', Presença: false, ValordeCompra: 125 },
  { Usuario: 'Joana Costa', Nickname: 'joanacosta', Presença: true, ValordeCompra: 250 }
];
