const options = [
  { Usuario: 'José Carlos da Silva', Presença: true, ValordeCompra: 120 },
  { Usuario: 'Ana Paula Martins', Presença: false, ValordeCompra: 200 },
  { Usuario: 'Carlos Henrique Souza', Presença: true, ValordeCompra: 350 },
  { Usuario: 'Mariana Oliveira', Presença: true, ValordeCompra: 75 },
  { Usuario: 'Rafael Mendes', Presença: false, ValordeCompra: 420 },
  { Usuario: 'Luciana Costa', Presença: true, ValordeCompra: 180 },
  { Usuario: 'Fernanda Lima', Presença: false, ValordeCompra: 95 },
  { Usuario: 'João Pedro Rocha', Presença: true, ValordeCompra: 260 },
  { Usuario: 'Tatiane Barbosa', Presença: false, ValordeCompra: 130 },
  { Usuario: 'Ricardo Santos', Presença: true, ValordeCompra: 400 },
  { Usuario: 'Paula Regina Campos', Presença: false, ValordeCompra: 60 },
  { Usuario: 'Bruno César Moreira', Presença: true, ValordeCompra: 150 },
  { Usuario: 'Débora Almeida', Presença: false, ValordeCompra: 300 },
  { Usuario: 'Tiago Nunes', Presença: true, ValordeCompra: 240 },
  { Usuario: 'Camila Freitas', Presença: false, ValordeCompra: 80 },
  { Usuario: 'Gustavo Araújo', Presença: true, ValordeCompra: 220 },
  { Usuario: 'Juliana Souza', Presença: true, ValordeCompra: 310 },
  { Usuario: 'Eduardo Lopes', Presença: false, ValordeCompra: 175 },
  { Usuario: 'Isabela Martins', Presença: true, ValordeCompra: 500 },
  { Usuario: 'Marcelo Ferreira', Presença: false, ValordeCompra: 140 },
];
